[package]
name = "geometrydash"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
minhook = "0.3.0"
winapi = { version = "0.3.9", features = ["libloaderapi", "memoryapi"] }
fmod = { path = "fmod", optional = true }

[features]
gd_fmod = ["fmod"]
